# -*- coding: utf-8 -*-
"""LLMを動かそう_sakanaAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1scleNMB5QokP7hm-o6svvZH1Kj4tFcqr
"""

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

# 1. load model
device = "cuda" if torch.cuda.is_available() else "cpu"
repo_id = "SakanaAI/TinySwallow-1.5B-Instruct"
model = AutoModelForCausalLM.from_pretrained(repo_id)
tokenizer = AutoTokenizer.from_pretrained(repo_id)
model.to(device)

# 2. prepare inputs
text = "生成AIについて簡単に教えてください。"
messages = [{"role": "user", "content": text}]
input_ids = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

print(messages)

print(input_ids)

# 3. generate
# input_idsは辞書形式なので、その中の['input_ids']テンソルを渡します
output_ids = model.generate(
    input_ids["input_ids"].to(device),
    max_new_tokens=1024,
)
print(output_ids)

print(output_ids[:, input_ids['input_ids'].shape[1] :])

output_ids = output_ids[:, input_ids['input_ids'].shape[1] :]
generated_text = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0]
print(generated_text)

# 2. prepare inputs
text = "あなた自身を自己紹介してください。"
messages = [{"role": "user", "content": text}]
input_ids = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt", return_dict=True)

# 3. generate
# 辞書を展開して渡すか、特定のキーを指定します
output_ids = model.generate(
    **input_ids.to(device),
    max_new_tokens=1024,
)

# 入力トークン分をスライスして除去
output_ids = output_ids[:, input_ids['input_ids'].shape[1] :]
generated_text = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0]
print(generated_text)

# 2. prepare inputs
text = "ブラウザで実行できる誕生年から年齢を計算するアプリを作って。"
messages = [{"role": "user", "content": text}]
# return_dict=Trueを追加して明示的に辞書を受け取るようにします
input_dict = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt", return_dict=True)

# 3. generate
# 辞書を展開して渡すことで、input_idsとattention_maskの両方が正しく渡されます
output_ids = model.generate(
    **input_dict.to(device),
    max_new_tokens=1024,
)

# 入力トークンの長さを取得してスライスします
output_ids = output_ids[:, input_dict['input_ids'].shape[1] :]
generated_text = tokenizer.batch_decode(output_ids, skip_special_tokens=True)[0]
print(generated_text)